// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	ad "github.com/xejarque/challenges/internal/domain/ad"

	mock "github.com/stretchr/testify/mock"
)

// AdRepository is an autogenerated mock type for the AdRepository type
type AdRepository struct {
	mock.Mock
}

type AdRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AdRepository) EXPECT() *AdRepository_Expecter {
	return &AdRepository_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields:
func (_m *AdRepository) FindAll() ([]ad.Ad, error) {
	ret := _m.Called()

	var r0 []ad.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]ad.Ad, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []ad.Ad); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ad.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type AdRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *AdRepository_Expecter) FindAll() *AdRepository_FindAll_Call {
	return &AdRepository_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *AdRepository_FindAll_Call) Run(run func()) *AdRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AdRepository_FindAll_Call) Return(_a0 []ad.Ad, _a1 error) *AdRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdRepository_FindAll_Call) RunAndReturn(run func() ([]ad.Ad, error)) *AdRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function with given fields: id
func (_m *AdRepository) FindById(id string) (ad.Ad, error) {
	ret := _m.Called(id)

	var r0 ad.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (ad.Ad, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) ad.Ad); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(ad.Ad)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type AdRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id string
func (_e *AdRepository_Expecter) FindById(id interface{}) *AdRepository_FindById_Call {
	return &AdRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *AdRepository_FindById_Call) Run(run func(id string)) *AdRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AdRepository_FindById_Call) Return(_a0 ad.Ad, _a1 error) *AdRepository_FindById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdRepository_FindById_Call) RunAndReturn(run func(string) (ad.Ad, error)) *AdRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Persist provides a mock function with given fields: _a0
func (_m *AdRepository) Persist(_a0 ad.Ad) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(ad.Ad) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdRepository_Persist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Persist'
type AdRepository_Persist_Call struct {
	*mock.Call
}

// Persist is a helper method to define mock.On call
//   - _a0 ad.Ad
func (_e *AdRepository_Expecter) Persist(_a0 interface{}) *AdRepository_Persist_Call {
	return &AdRepository_Persist_Call{Call: _e.mock.On("Persist", _a0)}
}

func (_c *AdRepository_Persist_Call) Run(run func(_a0 ad.Ad)) *AdRepository_Persist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ad.Ad))
	})
	return _c
}

func (_c *AdRepository_Persist_Call) Return(_a0 error) *AdRepository_Persist_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdRepository_Persist_Call) RunAndReturn(run func(ad.Ad) error) *AdRepository_Persist_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAdRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdRepository creates a new instance of AdRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdRepository(t mockConstructorTestingTNewAdRepository) *AdRepository {
	mock := &AdRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
